server.port=8080
spring.application.name=repro-app
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
